export const EXECUTION_BUDGETS = {
  MAX_SOURCE_CODE_BYTES: 64 * 1024, // 64 KiB
  MAX_TESTS_PER_EXERCISE: 50,
  MAX_STDIN_BYTES: 64 * 1024, // 64 KiB
  MAX_EXPECTED_STDOUT_BYTES: 64 * 1024, // 64 KiB
  DEFAULT_CPU_TIMEOUT_SECONDS: 2,
  MAX_ADMIN_CPU_TIMEOUT_SECONDS: 5,
  DEFAULT_WALL_TIMEOUT_SECONDS: 5,
  MAX_JOB_WALL_TIMEOUT_SECONDS: 60,
  DEFAULT_MEMORY_LIMIT_MIB: 128,
  MAX_ADMIN_MEMORY_LIMIT_MIB: 256,
  MAX_CAPTURED_OUTPUT_BYTES: 64 * 1024, // 64 KiB
  MAX_TEMP_DISK_MIB: 16,
  RUN_RATE_PER_MINUTE: 10,
  SUBMIT_RATE_PER_MINUTE: 5,
  MAX_ACTIVE_JOBS_PER_USER: 2,
} as const;

export const PYTHON_RUNTIME_LABEL = 'Python 3.14.7';

export const MEDIA_BUDGETS = {
  MAX_IMAGE_BYTES: 10 * 1024 * 1024, // 10 MB
  ALLOWED_IMAGE_MIME_TYPES: ['image/png', 'image/jpeg', 'image/webp'] as const,
  MAX_DECODED_PIXELS: 25_000_000,
} as const;

export const COURSE_STRUCTURE_LIMITS = {
  MAX_STEPS_PER_LESSON: 20,
  MIN_STEPS_PER_LESSON: 1,
  MAX_TAGS_PER_COURSE: 5,
  MAX_TAG_LENGTH: 30,
} as const;
